auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwords
auth_param basic realm "Squid Proxy"
auth_param basic credentialsttl 2 hours

acl authenticated proxy_auth REQUIRED

acl target dstdomain opencode.ai
acl target dstdomain models.dev
acl target dstdomain apigithub.com
acl target dstdomain api.github.com
acl target dstdomain api.githubcopilot.com


http_access allow CONNECT target authenticated
http_access deny all

http_port 3128
